data:
  file_path: 'datasets/jetnet/'
  test_size: 0.2
  random_state: 42
  data_args:
    jet_type: ['g','q', 't', 'w', 'z'] 
    data_dir: "datasets/jetnet"       # only selecting the kinematic features
    particle_features: ["etarel", "phirel", "ptrel"]
    num_particles: 30                  # NUmber of particles in each jet max 150
    jet_features: ["type", "pt", "eta", "mass"]
   # 'num_jets': 100,               # Total number of jets
    "download": True  # Automatic download

training:
  num_epochs: 50
  learning_rate: 0.01
  checkpoint_path: 'summary/best_uresnet_emd2.pth'
  device: 'cuda' 
  log_dir: 'test3'
  images: True

loss:
  loss_function: 'emd2_loss'


model:
  model_type: 'uresnet' 
  input_dim: 1
  num_classes: 5 

inference:
  train_name: 'uresnet'
  checkpoint_path: 'summary/best_uresnet_emd2.pth'
  save_dir: 'figures'
