data:
  file_path: 'datasets/jetnet/'
  test_size: 0.2
  random_state: 42
  data_args:
    jet_type: ['g','q', 't', 'w', 'z'] 
    data_dir: "datasets/jetnet"       # only selecting the kinematic features
    particle_features: ["etarel", "phirel", "ptrel"]
    num_particles: 120                  # NUmber of particles in each jet max 150
    jet_features: ["type", "pt", "eta", "mass"]
   # 'num_jets': 100,               # Total number of jets
    "download": True  # Automatic download

training:
  num_epochs: 50
  #learning_rate: 0.01
  learning_rate: 0.1
  checkpoint_path: 'summary/best_multiclass_model_120_autoencoder.pth'
  device: 'cuda' 
  log_dir: 'test'
  images: True

loss:
  loss_function: 'CrossEntropyLoss'


model:
  model_type: 'residual_autoencoder' 
  input_dim: 6
  output_dim: 5 
  layers: [128,64,32,64,128] 

inference:
  train_name: 'multiclass_residual_autoencoder'
  checkpoint_path: 'summary/best_multiclass_model_120_res_autoencoder.pth'
  save_dir: 'figures'
